=== infstka/CML-1c2s/XML/XML2/l21.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <xs:element name="faculty">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="uni">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="years" type="xs:string"/>
                            <xs:element name="ct" type="xs:string"/>
                            <xs:element name="ball" type="xs:string"/>
                            <xs:element name="plan" type="xs:string"/>
                            <xs:element name="city" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="uni">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="years" type="xs:string"/>
                            <xs:element name="ct" type="xs:string"/>
                            <xs:element name="ball" type="xs:string"/>
                            <xs:element name="plan" type="xs:string"/>
                            <xs:element name="city" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="uni">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="years" type="xs:string"/>
                            <xs:element name="ct" type="xs:string"/>
                            <xs:element name="ball" type="xs:string"/>
                            <xs:element name="plan" type="xs:string"/>
                            <xs:element name="city" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== infstka/CML-1c2s/XML/XML2/l21.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/css" href="lab1.css"?>
<faculty xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="l21.xsd">
    <uni>
        <name>БГУ</name>
        <years>4 года</years>
        <ct>Русский/белорусский, математика, физика</ct>
        <ball>Балл: 308</ball>
        <plan>Количество мест: 30</plan>
        <city>Минск</city>
    </uni>

    <uni>
        <name>БНТУ</name>
        <years>4 года</years>
        <ct>Русский/белорусский, математика, физика</ct>
        <ball>Балл: 319</ball>
        <plan>Количество мест: 40</plan>
        <city>Минск</city>
    </uni>

    <uni>
        <name>БГУИР</name>
        <years>4 года</years>
        <ct>Русский/белорусский, математика, физика</ct>
        <ball>Балл: 299</ball>
        <plan>Количество мест: 35</plan>
        <city>Минск</city>
    </uni>
</faculty>
